dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

language: node_js
node_js:
- '10'

before_install:
  - stty cols 80

notifications:
  email:
  - howardc93@gmail.com
  - aqc2109@columbia.edu
  - mjr127@case.edu
script:
- npm run build
- npm install -g serve
- npm run testcafe
# blocklist
branches:
  except:
  - l10n_master
